export const routeNames = {
  general: {
    landing: "/",
    login: "/login",
    addService: "/add-service",
    viewService: "/view-services",
    addProject: "/add-project",
    viewProjects: "/view-projects",
    addProduct: "/add-product",
    viewProducts: "/view-products",
    addJob: "/add-job",
    addJobCategory: "/add-job-category",
    viewJobCategory: "/view-job-category",
    viewJobs: "/view-jobs",
    jobApplications: "/job-applications",
    addTeam: "/add-team",
    viewTeams: "/view-teams",
    addBlog: "/add-blog",
    viewBlogs: "/view-blogs",
    addTestimonial: "/add-testimonial",
    viewTestimonial: "/view-testimonial",
    settings: "/settings",
    aboutUs: "/about-us",
  },
};
